name: "Setup Environment"
description: "Set up Python environment with dependencies and caching"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"
  install-type:
    description: "Type of installation: minimal, dev, or full"
    required: false
    default: "dev"
  os:
    description: "Operating system (for Qt dependencies)"
    required: false
    default: ${{ runner.os }}

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml
          requirements*.txt

    - name: Install Qt system dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dri \
          libglib2.0-0 \
          libegl1 \
          libxcb-xinerama0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxkbcommon-x11-0 \
          libdbus-1-3 \
          xvfb \
          x11-utils

    - name: Upgrade pip
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install package (minimal)
      if: inputs.install-type == 'minimal'
      shell: bash
      run: |
        pip install -e .

    - name: Install package (dev)
      if: inputs.install-type == 'dev'
      shell: bash
      run: |
        pip install -e ".[dev]"

    - name: Install package (full)
      if: inputs.install-type == 'full'
      shell: bash
      run: |
        pip install -e ".[dev,docs]"

    - name: Display Python info
      shell: bash
      run: |
        python --version
        pip --version
        pip list
